version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:12.19.0
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
  environment:
    NODE_ENV: test
    NODE_OPTIONS: --max_old_space_size=4096

ignore_master: &ignore_master
  branches:
    ignore:
      - master

jobs:
  # --------------------------------------------------------------------------
  # Phase 1: Setup
  # --------------------------------------------------------------------------
  setup:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: lock-{{ checksum "package-lock.json" }}

      # Save cache
      - save_cache:
          key: lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm ci

      # Persist workspace
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  # --------------------------------------------------------------------------
  # Phase 2: Lint
  # --------------------------------------------------------------------------
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: npm run test:lint

  # --------------------------------------------------------------------------
  # Phase 3: Unit
  # --------------------------------------------------------------------------
  test-unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit Tests
          command: npm run test:unit:coverage && npm run coverage

# Workflow definition
workflows:
  version: 2

  # Build and test after each commit
  commit:
    jobs:
      - setup:
          filters:
            <<: *ignore_master
      - lint:
          requires: [setup]
          filters:
            <<: *ignore_master
      - test-unit:
          requires: [lint]
          filters:
            <<: *ignore_master
